entreprise/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finance.urls')),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
]

finance/urls.py
from django.urls import path
from . import views

# definition of the application's urls
urlpatterns = [
    path('home', views.home, name='home'),
    path('listCompany',views.listCompany, name='listCompany'),
    path('addCompany', views.addCompany, name='addCompany'),
    path('editCompany/<int:id>', views.editCompany, name='editCompany'),
    path('deleteCompany/<int:id>', views.deleteCompany, name='deleteCompany'),
    path('summaryCompany/<int:id>', views.summaryCompany, name='summaryCompany'),
    path('addFormuCompta/<int:id>', views.addFormuCompta, name='addFormuCompta'),
    path('deleteFormuCompta/<int:id>/<int:id2>', views.deleteFormuCompta, name='deleteFormuCompta'),
    path('editFormuCompta/<int:id>/<int:id2>', views.editFormuCompta, name='editFormuCompta'),
    path('showGraph/<int:id>', views.showGraph, name='showGraph'),
    path('', views.homeRedirection, name='homeRedirection'),
]

finance/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=40, verbose_name="nom", unique=True)
    address = models.CharField(max_length=180, verbose_name="adresse")
    country = models.CharField(max_length=80, verbose_name="pays", default="Suisse")
    contact = models.CharField(max_length=100, verbose_name="personne de contact")

    class Meta:
        verbose_name = "Company"
        ordering = ['name']

    def __str__(self):
        return self.name

class FormuCompta(models.Model):
    company = models.ForeignKey('Company', on_delete=models.CASCADE )
    month = models.ForeignKey('Month', on_delete=models.CASCADE)
    year = models.ForeignKey('Year', on_delete=models.CASCADE)
    ca = models.FloatField(default=0.0, verbose_name="CA")
    frais_achat = models.FloatField(default=0.0, verbose_name="Frais d'achat")
    charges_sociales = models.FloatField(default=0.0, verbose_name="Charges sociales")
    fg = models.FloatField(default=0.0, verbose_name="Frais généraux")
    autres_frais = models.FloatField(default=0.0, verbose_name="Autres frais")
    ebitda = models.FloatField(default=0.0, verbose_name="EBITDA")
    credits_ct = models.FloatField(default=0.0, verbose_name="Crédits courts termes")
    credits_lt = models.FloatField(default=0.0, verbose_name="Crédits long termes")
    cashflow = models.FloatField(default=0.0, verbose_name="Cashflow")
    investissements = models.FloatField(default=0.0, verbose_name="Investissements")

    class Meta:
        verbose_name = "FormuCompta"
        ordering = ['-year', '-month']

    def __str__(self):
        return self.month.month + str(self.year)

class Month(models.Model):
    number = models.IntegerField(verbose_name="num", unique=True)
    month = models.CharField(max_length=20, verbose_name="mois", unique=True)

    class Meta:
        verbose_name = "Month"

    def __str__(self):
        return self.month

class Year(models.Model):
    year = models.IntegerField(verbose_name="année", unique=True)

    class Meta:
        verbose_name = "Year"

    def __str__(self):
        return str(self.year)

finance/forms.py
from django import forms
from django.db import models
from .models import Company, FormuCompta

# creation of the forms. most of them are derived from the models

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'

class FormuComptaForm(forms.ModelForm):
    class Meta:
        model = FormuCompta
        fields = ('month', 'year', 'ca', 'frais_achat', 'charges_sociales', 'fg', 'autres_frais', 'ebitda', 'credits_ct', 'credits_lt', 'cashflow', 'investissements')

finance/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.utils import timezone
from django.contrib.auth.models import User
from .forms import CompanyForm, FormuComptaForm
from .models import Company, FormuCompta
import os, time, datetime

# Create your views here.
def home(request):
    return render(request, 'finance/home.html', locals())

def homeRedirection(request):
    return redirect('home')

def listCompany(request):
    companies = Company.objects.all()
    return render(request, 'finance/listCompany.html', {'companies':companies})

def addCompany(request):
    # Build the form, either with the data posted,
    # or empty if the user accesses for the first time the page.
    form = CompanyForm(request.POST or None)
    if form.is_valid():
        form.save()
        validEntry = True

    # Whatever happens, we display the page of the form.
    return render(request, 'finance/addCompany.html', locals())

def editCompany(request,id):
    company = get_object_or_404(Company, id=id)
    form = CompanyForm(request.POST or None, instance=company)
    if form.is_valid():
        form.save()
        return redirect('listCompany')
    return render(request, 'finance/editCompany.html', {'form':form})

def deleteCompany(request,id):
    company = get_object_or_404(Company, id=id)
    company.delete()
    return redirect('listCompany')

def summaryCompany(request,id):
    company = get_object_or_404(Company, id=id)
    formuComptaForCompany = FormuCompta.objects.filter(company__id=company.id)
    return render(request, 'finance/summaryCompany.html', locals())

def addFormuCompta(request,id):
    company = get_object_or_404(Company, id=id)
    form = FormuComptaForm(request.POST or None)
    if form.is_valid():
        formTemp = form.save(commit=False)
        formucompta = FormuCompta(company = Company.objects.get(id=company.id), month = formTemp.month, year = formTemp.year, ca = formTemp.ca, frais_achat = formTemp.frais_achat, charges_sociales = formTemp.charges_sociales, fg = formTemp.fg, autres_frais = formTemp.autres_frais, ebitda = formTemp.ebitda, credits_ct = formTemp.credits_ct, credits_lt = formTemp.credits_lt, cashflow = formTemp.cashflow, investissements = formTemp.investissements)
        formucompta.save()
        return redirect('summaryCompany', id=company.id)
    return render(request, 'finance/addFormuCompta.html', locals())

def deleteFormuCompta(request,id,id2):
    formucompta = get_object_or_404(FormuCompta, id=id)
    company = get_object_or_404(Company, id=id2)
    formucompta.delete()
    return redirect('summaryCompany', id=company.id)

def editFormuCompta(request,id, id2):
    formucompta = get_object_or_404(FormuCompta, id=id)
    company = get_object_or_404(Company, id=id2)
    form = FormuComptaForm(request.POST or None, instance=formucompta)
    if form.is_valid():
        form.save()
        return redirect('summaryCompany', id=company.id)
    return render(request, 'finance/editFormuCompta.html', {'form':form})

def showGraph(request,id):
    company = get_object_or_404(Company, id=id)
    formuComptaForCompany = FormuCompta.objects.filter(company__id=company.id)
    return render(request, 'finance/showGraph.html', locals())

finance/templates/finance/addCompany.html
{% extends "base.html" %}
{% load static %}

{% block title %} ajouter société {% endblock %}

{% block cssAddition %}
<link rel="stylesheet" href="{% static 'css/addCompany.css' %}">
{% endblock %}

{% block mainTitle %} Ajouter une société {% endblock %}

{% block content %}

  <div class="ui middle aligned center aligned grid">
    <div class="column">
      <form class="ui form" id="formAddCompany" action="{% url "addCompany" %}" method="post">
        {% csrf_token %}
        <div class="ui segment">
          <div class="ui info message">
            <p>Le nom de la société</p>
          </div>
          <div class="inline fields">
            <div class="three wide field">
              {{ form.name.label_tag }}
            </div>
            <div class="thirteen wide field">
              {{ form.name }}
            </div>
          </div>
          <div class="ui info message">
            <p>L' adresse de la société</p>
          </div>
          <div class="inline fields">
            <div class="three wide field">
              {{ form.address.label_tag }}
            </div>
            <div class="thirteen wide field">
              {{ form.address }}
            </div>
          </div>
          <div class="ui info message">
            <p>Le pays de la société</p>
          </div>
          <div class="inline fields">
            <div class="three wide field">
              {{ form.country.label_tag }}
            </div>
            <div class="thirteen wide field">
              {{ form.country }}
            </div>
          </div>
          <div class="ui info message">
            <p>Personne de contact dans la société</p>
          </div>
          <div class="inline fields">
            <div class="three wide field">
              {{ form.contact.label_tag }}
            </div>
            <div class="thirteen wide field">
              {{ form.contact }}
            </div>
          </div>
          <button type="submit" class="ui fluid blue button">Enregistrer</button>
        </div>
      </form>
      <div class="ui warning message">
        <ul>
          <li>Respectez les règles en bleu pour chaque champs</li>
        </ul>
        {{ form.non_field_errors }}
        {{ form.name.errors }}
        {{ form.address.errors }}
        {{ form.country.errors }}
        {{ form.contact.errors }}
      </div>
      {% if validEntry %}
        <div class="ui positive message">Nouvelle société ajoutée
          <button class="ui green tiny button" id="btnAddCompanyBacktoHome" onclick="location.href='{% url "home" %}';">
            Retour
          </button>
        </div>
      {% endif %}
    </div>
  </div>

{% endblock %}

{% block javascript_jq %}
  <script>
    console.log("asfsaasdfasfsafasfdasfasfas");
  </script>

{% endblock %}

finance/templates/finance/addFormuCompta.html
{% extends "base.html" %}
{% load static %}

{% block title %} ajout formulaire {% endblock %}

{% block cssAddition %}
<link rel="stylesheet" href="{% static 'css/addFormuCompta.css' %}">
{% endblock %}

{% block mainTitle %} Ajouter un formumlaire {% endblock %}

{% block content %}

  <div class="ui center aligned grid">
    <div class="left aligned  column">
      <form class="ui form" id="formAddFormuCompta" action="{% url "addFormuCompta" company.id %}" method="post">
        {% csrf_token %}
        <div class="ui segment">
          <div class="inline fields">
            <div class="four wide field">
              {{ form.month.label_tag }}
            </div>
            <div class="four wide field">
              {{ form.month }}
            </div>
            <div class="four wide field">
              {{ form.year.label_tag }}
            </div>
            <div class="four wide field">
              {{ form.year }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.ca.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.ca }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.frais_achat.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.frais_achat }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.charges_sociales.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.charges_sociales }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.fg.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.fg }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.autres_frais.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.autres_frais }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.ebitda.label_tag }}
            </div>
            <div class="nine wide field">
              {{ form.ebitda }}
            </div>
            <div class="three wide field">
              <button class="ui tiny blue button" type="button" onclick="calculate();">
                calculer
              </button>
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.credits_ct.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.credits_ct }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.credits_lt.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.credits_lt }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.cashflow.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.cashflow }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.investissements.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.investissements }}
            </div>
          </div>
          <button type="submit" class="ui fluid blue button">Enregistrer</button>
        </div>
      </form>
      <div class="ui warning message">
        <ul>
          <li>Vous serez directement redirigé à la page de la société</li>
        </ul>
        {{ form.non_field_errors }}
        {{ form.company.errors }}
        {{ form.month.errors }}
        {{ form.year.errors }}
        {{ form.ca.errors }}
        {{ form.frais_achat.errors }}
        {{ form.charges_sociales.errors }}
        {{ form.fg.errors }}
        {{ form.autres_frais.errors }}
        {{ form.ebitda.errors }}
        {{ form.credits_ct.errors }}
        {{ form.credits_lt.errors }}
        {{ form.cashflow.errors }}
        {{ form.investissements.errors }}
      </div>
    </div>
  </div>
{% endblock %}

{% block javascript_jq %}
  <script>

    function calculate (){
      const ca = $('#id_ca').val();
      const fa = $('#id_frais_achat').val();
      const cs = $('#id_charges_sociales').val();
      const fg = $('#id_fg').val();
      const af = $('#id_autres_frais').val();
      $('#id_ebitda').val(ca-fa-cs-fg-af);

    }

  </script>

{% endblock %}

finance/templates/finance/editCompany.html
{% extends "base.html" %}
{% load static %}

{% block title %} editCompany {% endblock %}

{% block cssAddition %}
<link rel="stylesheet" href="{% static 'css/editCompany.css' %}">
{% endblock %}

{% block mainTitle %} Modifier une société {% endblock %}

{% block content %}

  <div class="ui middle aligned center aligned grid">
    <div class="column">
      <form class="ui form" method="post">
        {% csrf_token %}
        <div class="ui segment">
          <div class="inline fields">
            <div class="three wide field">
              {{ form.name.label_tag }}
            </div>
            <div class="thirteen wide field">
              {{ form.name }}
            </div>
          </div>
          <div class="inline fields">
            <div class="three wide field">
              {{ form.address.label_tag }}
            </div>
            <div class="thirteen wide field">
              {{ form.address }}
            </div>
          </div>
          <div class="inline fields">
            <div class="three wide field">
              {{ form.country.label_tag }}
            </div>
            <div class="thirteen wide field">
              {{ form.country }}
            </div>
          </div>
          <div class="inline fields">
            <div class="three wide field">
              {{ form.contact.label_tag }}
            </div>
            <div class="thirteen wide field">
              {{ form.contact }}
            </div>
          </div>
          <button type="submit" class="ui fluid blue button">Enregistrer modification(s)</button>
        </div>
     </form>
     <div class="ui warning message">
       <ul>
         <li>Vous serez directement redirigé à la liste des sociétés</li>
       </ul>
       {{ form.non_field_errors }}
       {{ form.name.errors }}
       {{ form.address.errors }}
       {{ form.country.errors }}
       {{ form.contact.errors }}
     </div>
    </div>
  </div>

{% endblock %}

finance/templates/finance/editFormuCompta.html
{% extends "base.html" %}
{% load static %}

{% block title %} edition formulaire {% endblock %}

{% block cssAddition %}
<link rel="stylesheet" href="{% static 'css/editFormuCompta.css' %}">
{% endblock %}

{% block mainTitle %} Modifier un formumlaire {% endblock %}

{% block content %}

  <div class="ui center aligned grid">
    <div class="left aligned  column">
      <form class="ui form" method="post">
        {% csrf_token %}
        <div class="ui segment">
          <div class="inline fields">
            <div class="four wide field">
              {{ form.month.label_tag }}
            </div>
            <div class="four wide field">
              {{ form.month }}
            </div>
            <div class="four wide field">
              {{ form.year.label_tag }}
            </div>
            <div class="four wide field">
              {{ form.year }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.ca.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.ca }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.frais_achat.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.frais_achat }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.charges_sociales.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.charges_sociales }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.fg.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.fg }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.autres_frais.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.autres_frais }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.ebitda.label_tag }}
            </div>
            <div class="nine wide field">
              {{ form.ebitda }}
            </div>
            <div class="three wide field">
              <button class="ui tiny blue button" type="button" onclick="calculate();">
                calculer
              </button>
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.credits_ct.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.credits_ct }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.credits_lt.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.credits_lt }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.cashflow.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.cashflow }}
            </div>
          </div>
          <div class="inline fields">
            <div class="four wide field">
              {{ form.investissements.label_tag }}
            </div>
            <div class="twelve wide field">
              {{ form.investissements }}
            </div>
          </div>
          <button type="submit" class="ui fluid blue button">Enregistrer modification(s)</button>
        </div>
      </form>
      <div class="ui warning message">
        <ul>
          <li>Vous serez directement redirigé à la page de la société</li>
        </ul>
        {{ form.non_field_errors }}
        {{ form.company.errors }}
        {{ form.month.errors }}
        {{ form.year.errors }}
        {{ form.ca.errors }}
        {{ form.frais_achat.errors }}
        {{ form.charges_sociales.errors }}
        {{ form.fg.errors }}
        {{ form.autres_frais.errors }}
        {{ form.ebitda.errors }}
        {{ form.credits_ct.errors }}
        {{ form.credits_lt.errors }}
        {{ form.cashflow.errors }}
        {{ form.investissements.errors }}
      </div>
    </div>
  </div>
{% endblock %}

{% block javascript_jq %}
  <script>

    function calculate (){
      const ca = $('#id_ca').val();
      const fa = $('#id_frais_achat').val();
      const cs = $('#id_charges_sociales').val();
      const fg = $('#id_fg').val();
      const af = $('#id_autres_frais').val();
      $('#id_ebitda').val(ca-fa-cs-fg-af);

    }

  </script>

{% endblock %}

finance/templates/finance/home.html
{% extends "base.html" %}
{% load static %}

{% block title %} home {% endblock %}

{% block cssAddition %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block mainTitle %} Home page {% endblock %}

{% block content %}
  <div class="ui middle aligned center aligned grid">
    <div class="column">
      <div class="raw">
        <button class="ui fluid blue large button" onclick="location.href='{% url "listCompany" %}';">
          Liste des sociétés
        </button>
      </div>
      {% if user.is_staff %}
      <div class="raw">
        <button class="ui fluid blue large button" onclick="location.href='{% url "addCompany" %}';">
          Ajouter une société
        </button>
      </div>
      <div class="raw">
        <button class="ui fluid blue large button"onclick="location.href='admin/';">
          Administration (droits utilisateurs)
        </button>
      </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

finance/templates/finance/listCompany.html
{% extends "base.html" %}
{% load static %}

{% block title %} listCompany {% endblock %}

{% block cssAddition %}
<link rel="stylesheet" href="{% static 'css/listCompany.css' %}">
{% endblock %}

{% block mainTitle %} Liste des sociétés{% endblock %}

{% block content %}
  {% if user.is_staff %}
  <button class="ui blue medium button" id="btnAddCompany" onclick="location.href='{% url "addCompany" %}';">
    Ajouter une société
  </button>
  {% endif %}
  {% for company in companies %}
    <div class="ui raised segment">
      <div class="ui stackable grid">
        <div class="six wide column">
          <div class="ui medium header">{{ company.name }}</div>
          <p>{{ company.address }}</p>
        </div>
        <div class="two wide center aligned column">
          <p><b>Pays</b></p>
          <p>{{ company.country }}</p>
        </div>
        <div class="two wide center aligned column">
          <p><b>Contact</b></p>
          <p>{{ company.contact }}</p>
        </div>
        <div class="two wide center aligned column">
          {% if user.is_staff %}
          <button class="ui icon button" onclick="location.href='{% url "deleteCompany" company.id %}';">
            <i class="trash alternate icon"></i>
          </button>
          {% endif %}
        </div>
        <div class="two wide center aligned column">
          {% if user.is_staff %}
          <button class="ui icon button" onclick="location.href='{% url "editCompany" company.id %}';">
            <i class=" edit icon"></i>
          </button>
          {% endif %}
        </div>
        <div class="two wide center aligned column">
          <button class="circular large ui blue icon button" onclick="location.href='{% url "summaryCompany" company.id %}';">
            <i class=" white large chevron right icon"></i>
          </button>
        </div>
      </div>
    </div>
  {% empty %}
    <p>Aucune société dans la liste.</p>
  {% endfor %}
{% endblock %}

finance/templates/finance/showGraph.html
{% extends "base.html" %}
{% load static %}

{% block title %} home {% endblock %}

{% block cssAddition %}
<link rel="stylesheet" href="{% static 'css/showGraph.css' %}">
{% endblock %}

{% block mainTitle %} {{ company.name }} {% endblock %}

{% block content %}
<div id="container" style="width:100%; height:600px;"></div>
{% endblock %}

{% block javascript_jq %}
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <script>
    var xAxisCategories = [];
    var caData = [];
    var faData = [];
    var ebitdaData = [];
    var csData = [];
    var fgData = [];
    var afData = [];
    var cctData = [];
    var cltData = [];
    var cashflowData = [];
    var investissementsData = [];

    {% for formu in formuComptaForCompany %}
      tempMonth = "{{ formu.month }}";
      tempYear = "{{ formu.year }}";
      temp = tempYear.concat(" ",tempMonth);
      xAxisCategories.push(temp);

      caTemp = "{{ formu.ca }}".replace(',','.');
      caData.push(parseFloat(caTemp));

      faTemp = "{{ formu.frais_achat }}".replace(',','.');
      faData.push(parseFloat(faTemp));

      csTemp = "{{ formu.charges_sociales }}".replace(',','.');
      csData.push(parseFloat(csTemp));

      fgTemp = "{{ formu.fg }}".replace(',','.');
      fgData.push(parseFloat(fgTemp));

      afTemp = "{{ formu.autres_frais }}".replace(',','.');
      afData.push(parseFloat(afTemp));

      ebitdaTemp = "{{ formu.ebitda }}".replace(',','.');
      ebitdaData.push(parseFloat(ebitdaTemp));

      cctTemp = "{{ formu.credits_ct }}".replace(',','.');
      cctData.push(parseFloat(cctTemp));

      cltTemp = "{{ formu.credits_lt }}".replace(',','.');
      cltData.push(parseFloat(cltTemp));

      cashflowTemp = "{{ formu.cashflow }}".replace(',','.');
      cashflowData.push(parseFloat(cashflowTemp));

      investissementsTemp = "{{ formu.investissements }}".replace(',','.');
      investissementsData.push(parseFloat(investissementsTemp));

    {% empty %}
    {% endfor %}

    Highcharts.chart('container', {
        title: {
            text: 'Evolutaion financière'
        },
        xAxis: {
            categories: xAxisCategories
        },
        yAxis: {
            title: {
                text: 'CHF'
            }
        },

        series: [{
            name: 'CA',
            data: caData,
            lineWidth: 2
        }, {
            name: 'Frais achat',
            data: faData,
            lineWidth: 2
        },{
            name: 'Charges sociales',
            data: csData,
            lineWidth: 2
        },{
            name: 'Frais généraux',
            data: fgData,
            lineWidth: 2
        },{
            name: 'Autres Frais',
            data: afData,
            lineWidth: 2
        },{
            name: 'EBITDA',
            data: ebitdaData,
            lineWidth: 2
        },{
            name: 'Crédits CT',
            data: cctData,
            lineWidth: 2
        },{
            name: 'Crédits LT',
            data: cltData,
            lineWidth: 2
        },{
            name: 'Cashflow',
            data: cashflowData,
            lineWidth: 2
        },{
            name: 'Investissements',
            data: investissementsData,
            lineWidth: 2
        }
        ]
    });

  </script>

{% endblock %}